constr:
  TestConstr:
  MCell:
    isFlat: true
    argNum: 2
  MListSeg:
    inPort: list
    args:
      0:
        isPointer: true # For any instance of this construct, isPointer=true means this field is always a pointer
        outPort: list
      1:
        inTable: true
        inPort: list
        outPort: list
  MList:
    argNum: 1
  MQueue:
    args:
      0:
        inTable: true
  MNode:
    isFlat: true
    argNum: 3
  MTree:
    args:
      0:
        inTable: true
