/**
 * This file contains a parser that takes an input goal string and produces a
 * heap state:
 *   1. Parsing the separation-logic formulas from the goal string (using the
        separation-logic parser generated by peggy from sep-grammar.g);
 *   2. Transforming the tree into a heap state.
 */

// @ts-ignore
import { parse as sepParse } from './sep-grammar.g';

import type { Goal } from './sepGrammar.types';

export function parse(input: string): Goal {
  return sepParse(input) as Goal;
}
