/**
 * This file contains a parser that takes an input goal string and produces a
 * heap state:
 *   1. Parsing the separation-logic formulas from the goal string (using the
        separation-logic parser generated by peggy from sep-grammar.g);
 *   2. Transforming the tree into a heap state.
 */

// @ts-ignore
import { parse as sepParse } from './sep-grammar.g';
import * as Sep from './sep-grammar.types';

// -- AST Types ----------------------------------------------------------------

export type Goal = MaybeHProp[];

export type MaybeHProp = HProp | string;

export class HProp {
  constructor(
    public op: string,
    public args: HPropArg[],
    public ctx?: HPropCtx,
    public binder?: string
  ) {}
}

export type HPropArg = HProp | Term | Term[];

export type HPropCtx = Sep.HPropCtx;

export type Term = Value | Symbol | string;

// Compared to Sep.Value, Value is a class in order to use `instanceof`
export class Value {
  constructor(
    public op: string,
    public args: Term[]
  ) {}
}

export class Symbol {
  constructor(
    public isGlobal: boolean,
    public uid: string,
    public label: string
  ) {}
}

// -- Parsing ------------------------------------------------------------------

export function parse(input: string) {
  const sepGoal = sepParse(input) as Sep.Goal;
  let goal: Goal = convertGoal(sepGoal);
  // flatten stars, conjs, disjs
  goal.forEach((seg: MaybeHProp) => {
    if (seg instanceof HProp) flatten(seg);
  });
  // aggregate pures, points-tos
  goal = goal.map((seg: MaybeHProp) =>
    seg instanceof HProp ? aggregate(seg) : seg
  );
  // resolve symbols and lift exists
  goal = resolveSymbols(goal);

  return goal;
}

function convertGoal(goal: Sep.Goal): Goal {
  return goal.map(convertMaybeHProp);

  function convertValue(x: Sep.Value): Value {
    return new Value(x.op, x.args.map(convertMaybeValue));
  }

  function convertMaybeValue(x: Sep.MaybeValue): Term {
    return typeof x === 'object' ? convertValue(x) : x;
  }

  function convertHPropArg(x: Sep.HPropArg): HPropArg {
    if (Array.isArray(x)) return x.map(convertMaybeValue);
    if (typeof x === 'object' && 'kind' in x) {
      if (x.kind === 'hprop') return convertHProp(x as Sep.HProp);
      if (x.kind === 'value') return convertValue(x as Sep.Value);
    }
    return x;
  }

  function convertHProp(x: Sep.HProp): HProp {
    return new HProp(x.op, x.args.map(convertHPropArg), x.ctx, x.binder);
  }

  function convertMaybeHProp(x: Sep.MaybeHProp): MaybeHProp {
    return typeof x === 'object' ? convertHProp(x) : x;
  }
}

/**
 * Flatten nestest binary ops (e.g. `Star`s) into n-ary op (e.g. `Stars`).
 * Mutate in place.
 */
function flatten(hprop: HProp): void {
  const toFlattenOps = ['Star', 'Conj', 'Disj'];

  function rec(x: HProp): void {
    x.args.forEach((arg: HPropArg) => {
      if (arg instanceof HProp) rec(arg);
    });
    if (toFlattenOps.includes(x.op)) {
      const op = x.op + 's';
      x.op = op;
      x.args = x.args.flatMap((a: HPropArg) =>
        a instanceof HProp && a.op === op ? a.args : [a]
      );
    }
  }

  rec(hprop);
}

/**
 * Aggregate repeated `Pure` and `PointsTo` in `Stars`. E.g., tranform
 * `Stars(Pure(P1), ..., Pure(Pn), ...)` into `Stars(Pures(Pure(P1), ..., Pure(Pn)), ...)`.
 */
function aggregate(hprop: HProp): HProp {
  const toCoalesceOps = ['Pure', 'PointsTo'];

  function rec(x: HProp, op: string): HProp {
    const isOp = (y: HPropArg) => y instanceof HProp && y.op === op;
    const notOp = (y: HPropArg) => !isOp(y);
    const args = x.args.map((arg) =>
      arg instanceof HProp ? rec(arg, op) : arg
    );
    if (x.op === 'Stars') {
      const ops: HProp = {
        op: op + 's',
        args: args.filter(isOp),
      };
      if (ops.args.length !== 0)
        return new HProp(x.op, [ops, ...args.filter(notOp)], x.ctx, x.binder);
    }
    return new HProp(x.op, args, x.ctx, x.binder);
  }

  let x = hprop;
  toCoalesceOps.forEach((op) => (x = rec(x, op)));
  return x;
}

/**
 * Resolve symbols and lift local [Exist] quantifiers to the global scope.
 */
function resolveSymbols(goal: Goal): Goal {
  const gensym: Record<string, number> = {};
  const ctx: Record<string, Symbol> = {};

  function next(prefix: string): number {
    if (!(prefix in gensym)) gensym[prefix] = 0;
    return gensym[prefix]++;
  }

  function resolve(s: string): Symbol | string {
    // return s in ctx ? ctx[s] : { isGlobal: true, uid: s, label: s }; // TODO
    return s in ctx ? ctx[s] : s;
  }

  function register(s: string): void {
    const num = next(s);
    ctx[s] = new Symbol(false, s + '$' + num, `${s}${num}`);
  }

  return goal.map((x) => (x instanceof HProp ? resolveHProp(x) : x));

  function resolveHProp(x: HProp): HProp {
    switch (x.op) {
      case 'Exist': {
        assertArgCount(x.args, 2, 'Exist');
        assertArgType(
          typeof x.args[0] === 'string',
          x.args[0],
          'string',
          'Exist'
        );
        assertArgType(x.args[1] instanceof HProp, x.args[1], 'HProp', 'Exist');

        const binder = x.args[0] as string;
        register(binder);
        return resolveHProp(x.args[1] as HProp);
      }
      default:
        return new HProp(x.op, x.args.map(resolveHPropArg), x.ctx, x.binder);
    }
  }

  function resolveHPropArg(x: HPropArg): HPropArg {
    if (x instanceof HProp) return resolveHProp(x);
    if (Array.isArray(x)) return x.map(resolveTerm);
    return resolveTerm(x as Term);
  }

  function resolveTerm(x: Term): Term {
    if (x instanceof Value) return resolveValue(x);
    return resolve(x as string);
  }

  function resolveValue(x: Value): Value {
    return new Value(x.op, x.args.map(resolveTerm));
  }

  function assertArgCount(args: unknown[], expected: number, name: string) {
    if (args.length !== expected) {
      throw new Error(
        `'${name}' expects ${expected} arguments, got ${args.length}`
      );
    }
  }

  function assertArgType(
    check: boolean,
    x: unknown,
    expected: string,
    name: string
  ) {
    if (!check) {
      throw new Error(
        `'${name}' arg expects ${expected}, got ${JSON.stringify(x)}`
      );
    }
  }
}
