/**
 * This file contains a parser that takes an input goal string and produces a
 * heap state:
 *   1. Parsing the separation-logic formulas from the goal string (using the
        separation-logic parser generated by peggy from sep-grammar.g);
 *   2. Transforming the tree into a heap state.
 */

// @ts-ignore
import { parse as sepParse } from './sep-grammar.g';

// -- AST Types ----------------------------------------------------------------

export type Goal = MaybeHProp[];

export type MaybeHProp = HProp | string;

export type HPropCtx = 'PRE' | 'POST';

export type MaybeValue = Value | MaybeSymbol;

export function MaybeValue_isValue(x: MaybeValue): x is Value {
  return typeof x === 'object' && 'op' in x;
}

export interface Value {
  op: string;
  args: MaybeValue[];
}

export type HPropArg = HProp | MaybeSymbol | MaybeValue[];

export interface HProp {
  op: string;
  args: HPropArg[];
  ctx?: HPropCtx;
  binder?: string; // hypothesis name (used in iris)
}

export type Uid = string;

export interface Symbol {
  isGlobal: boolean;
  uid: Uid;
  label: string;
}

function isString(x: unknown): x is string {
  return typeof x === 'string';
}

export type MaybeSymbol = Symbol | string;

export function MaybeHProp_isHProp(x: MaybeHProp): x is HProp {
  return typeof x === 'object';
}

export function HPropArg_isHProp(x: HPropArg): x is HProp {
  return typeof x === 'object' && 'op' in x;
}

export function HPropArg_isMaybeValues(x: HPropArg): x is MaybeValue[] {
  return Array.isArray(x);
}

// -- Parsing ------------------------------------------------------------------

export function parse(input: string) {
  let goal = sepParse(input) as Goal;
  // flatten stars, conjs, disjs
  goal.forEach((seg: MaybeHProp) => {
    if (MaybeHProp_isHProp(seg)) flatten(seg);
  });
  // aggregate pures, points-tos
  goal = goal.map((seg: MaybeHProp) =>
    MaybeHProp_isHProp(seg) ? aggregate(seg) : seg
  );
  // resolve symbols and lift exists
  goal = resolveSymbols(goal);

  return goal;
}

/**
 * Flatten nestest binary ops (e.g. `Star`s) into n-ary op (e.g. `Stars`).
 * Mutate in place.
 */
function flatten(hprop: HProp): void {
  const toFlattenOps = ['Star', 'Conj', 'Disj'];

  function rec(x: HProp): void {
    x.args.forEach((arg: HPropArg) => {
      if (HPropArg_isHProp(arg)) rec(arg);
    });
    if (toFlattenOps.includes(x.op)) {
      const op = x.op + 's';
      x.op = op;
      x.args = x.args.flatMap((a: HPropArg) =>
        HPropArg_isHProp(a) && a.op === op ? a.args : [a]
      );
    }
  }

  rec(hprop);
}

/**
 * Aggregate repeated `Pure` and `PointsTo` in `Stars`. E.g., tranform
 * `Stars(Pure(P1), ..., Pure(Pn), ...)` into `Stars(Pures(Pure(P1), ..., Pure(Pn)), ...)`.
 */
function aggregate(hprop: HProp): HProp {
  const toCoalesceOps = ['Pure', 'PointsTo'];

  function rec(x: HProp, op: string): HProp {
    const isOp = (y: HPropArg) => HPropArg_isHProp(y) && y.op === op;
    const notOp = (y: HPropArg) => !isOp(y);
    const args = x.args.map((arg) =>
      HPropArg_isHProp(arg) ? rec(arg, op) : arg
    );
    if (x.op === 'Stars') {
      const ops: HProp = {
        op: op + 's',
        args: args.filter(isOp),
      };
      if (ops.args.length !== 0)
        return {
          op: x.op,
          args: [ops, ...args.filter(notOp)],
          ...(x.ctx !== undefined && { ctx: x.ctx }),
          ...(x.binder !== undefined && { binder: x.binder }),
        };
    }
    return {
      op: x.op,
      args: args,
      ...(x.ctx !== undefined && { ctx: x.ctx }),
      ...(x.binder !== undefined && { binder: x.binder }),
    };
  }

  let x = hprop;
  toCoalesceOps.forEach((op) => (x = rec(x, op)));
  return x;
}

/**
 * Resolve symbols and lift local [Exist] quantifiers to the global scope.
 */
function resolveSymbols(goal: Goal): Goal {
  const gensym: Record<string, number> = {};
  const ctx: Record<string, Symbol> = {};

  function next(prefix: string): number {
    if (!(prefix in gensym)) gensym[prefix] = 0;
    return gensym[prefix]++;
  }

  function resolve(s: string): Symbol {
    return s in ctx ? ctx[s] : { isGlobal: true, uid: s, label: s };
  }

  function register(s: string): void {
    const num = next(s);
    ctx[s] = {
      isGlobal: false,
      uid: s + '$' + num,
      label: `${s}${num}`,
    };
  }

  return goal.map((x: MaybeHProp) =>
    MaybeHProp_isHProp(x) ? resolveHProp(x) : x
  );

  function resolveHProp(x: HProp): HProp {
    switch (x.op) {
      case 'Exist': {
        assertArgCount(x.args, 2, 'Exist');
        assertArgType(isString(x.args[0]), x.args[0], 'string', 'Exist');
        assertArgType(HPropArg_isHProp(x.args[1]), x.args[1], 'HProp', 'Exist');

        const binder = x.args[0] as string;
        register(binder);
        return resolveHProp(x.args[1] as HProp);
      }
      default: {
        return {
          op: x.op,
          args: x.args.map((y) => resolveHPropArg(y)),
          ...(x.ctx !== undefined && { ctx: x.ctx }),
          ...(x.binder !== undefined && { binder: x.binder }),
        };
      }
    }
  }

  function resolveHPropArg(x: HPropArg): HPropArg {
    if (HPropArg_isHProp(x)) return resolveHProp(x);
    if (HPropArg_isMaybeValues(x)) return x.map((y) => resolveMaybeValue(y));
    if (typeof x === 'string' && x in ctx) return resolve(x);
    return x;
  }

  function resolveMaybeValue(x: MaybeValue): MaybeValue {
    if (MaybeValue_isValue(x)) return resolveValue(x);
    if (typeof x === 'string' && x in ctx) return resolve(x);
    return x;
  }

  function resolveValue(x: Value): Value {
    return { op: x.op, args: x.args.map((y) => resolveMaybeValue(y)) };
  }

  function assertArgCount(args: unknown[], expected: number, name: string) {
    if (args.length !== expected) {
      throw new Error(
        `'${name}' expects ${expected} arguments, got ${args.length}`
      );
    }
  }

  function assertArgType(
    check: boolean,
    x: unknown,
    expected: string,
    name: string
  ) {
    if (!check) {
      throw new Error(
        `'${name}' arg expects ${expected}, got ${JSON.stringify(x)}`
      );
    }
  }
}
